### PR TITLE
Add tag prefix argument

### PR DESCRIPTION
**Pull request by shiipou**
Tag prefix argument allow action's user to add a prefix before the tag you will push.

### CODE REVIEW

**Comment by elgohr** [comment]
Hey, why would people want to do that? Could be achieved by prefixing a branch or using https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#tags-1

**Comment by shiipou** [comment]
> 
> 
> Hey, why would people want to do that? Could be achieved by prefixing a branch or using https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#tags-1

It can be useful if you build your image for multiple architectures.
For example, If you build for ARM, ARM64, and amd64, the prefix allow you to build your image on different tags. After having all thoses tags build for each arch, you can use docker manifest to create the latest tag that can be used on all arch.

```yml
name: Build Docker Image
on: [push]
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: 
      - self-hosted 
      - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ARM, ARM64, AMD64]
    steps:
    - name: Checkout code from Git repository
      uses: actions/checkout@v1
    - name: Publish to Docker
      uses: shiipou/Publish-Docker-Github-Action@master
      with:
        name: shiipou/labo/gc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: false
        cache: true
        tag_prefix: ${{ matrix.os }}-

  publish:
    name: Publish
    runs-on:
      - self-hosted
    steps:
    - run: |
        docker manifest create docker.pkg.github.com/shiishii/labo/gc:latest \
          docker.pkg.github.com/shiishii/labo/gc:AMD64-latest \
          docker.pkg.github.com/shiishii/labo/gc:ARM-latest \
          docker.pkg.github.com/shiishii/labo/gc:ARM64-latest
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
       docker push docker.pkg.github.com/shiishii/labo/gc:latest
```

**Comment by elgohr** [comment]
I would like to avoid something like `tag_prefix`, as there is always somebody arguing why it isn't `tag_suffix` ;-)  

Nevertheless, Matrix builds are a good starting point.  
I would prefer that the action itself would care about matrix builds, without a configuration.

**Comment by elgohr** [comment]
https://github.community/t5/GitHub-Actions/React-on-matrix-build-within-Action/m-p/56636#M9946

**Pull request closed without merging**
