### PR TITLE
Update README: Add how to use dynamic tag names

### PR DESCRIPTION
**Pull request by luigi311**
This will show people how to use dynamic tag names useful for creating version tags automatically.

### CODE REVIEW

**Comment by elgohr** [comment]
Thank you for the PR and the idea for the documetation!
Could we probably have a different example? There is a reason why `snapshot` isn't just using the SHA (https://github.com/elgohr/Publish-Docker-Github-Action#snapshot).

**Comment by luigi311** [comment]
This will not be a SHA. This will be the name of the version for your github release. Such as for this branch if this was being published to docker when you create the github release 2.14 it will push your changes to tags latest and 2.14.

**Comment by luigi311** [comment]
Granted that is only valid when a release is done. I think you are right if this is set to run on pushs. Let me change the example to only run on releases and not pushes

**Comment by luigi311** [comment]
@elgohr 
The example is more complete now and will only run on github releases now so it will publish to latest and whatever the new release is called, 2.14 in the case of the example provided.

**Comment by elgohr** [comment]
Thank you very much :)

**Pull request merged**
